/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getData
 * Signature: ()LA;
 */
JNIEXPORT jobject JNICALL Java_JNITest_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
